# Action to automatically pull content of main branch into gh-pages
# whenever main content is modified. Site will then be auto-deployed

name: 🔄 Sync main to Website
on:
#   push:
#     branches:
#       - main
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 5 * * 6' # Every Saturday morning.

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          FROM_BRANCH: main
          TO_BRANCH: gh-pages
          PULL_REQUEST_TITLE: '[AUTO] Update docs site'
          PULL_REQUEST_BODY: |
            Merging main into gh-pages, to be deployed to [awesome-privacy.xyz](https://awesome-privacy.xyz/).
