# Pushes the contents of the repo to the Codeberg mirror
name: 🪞 Mirror to Codeberg
on:
  push:
    branches: [ 'main' ]    
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 5 * * 6'
jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "git@codeberg.org:alicia/awesome-privacy.git"
          ssh_private_key: ${{ secrets.CODEBERG_SSH }}
